#!/usr/bin/env bash

BUILD_DIR=${BUILD_DIR:-build}
ADOC=${ADOC:-README.adoc}
REMOTE_REPO=${REMOTE_REPO:-`git config --get remote.origin.url`} || :
GENERATE_PDF=${GENERATE_PDF:-false}
SERVE_PORT=${SERVE_PORT:-5001}
