#!/usr/bin/env bash
set -eou pipefail

BASE_DIR=${BASE_DIR:-$PWD}
BUILDER_DIR=`cd "$(dirname "$0")"; pwd -P`

cd "$BASE_DIR"
echo "Base dir is \"$PWD\"."

config=build.conf
defaults=~/.${0##*/}
source ./$config 2>&- && {
  echo "File \"$config\" found. Merging it with defaults ($defaults)."
} || {
  echo "File \"$config\" not found. Using defaults ($defaults)."
}
[ -f "$BUILDER_DIR" ] || (cd; ln -sf ${BUILDER_DIR##$HOME/}/$config $defaults)
source "$defaults"

docker-asciidoctor() {
  case $1 in
    asciidoctor) echo "Generating HTML version ...";;
    asciidoctor-pdf) echo "Generating PDF version ...";;
  esac
  docker run -e TZ=America/Sao_Paulo -it --rm \
    -v "$PWD":/documents \
    asciidoctor/docker-asciidoctor "$@"
}

html() {
  local tag
  local attrs
  local production=false
  while [ "${1:-}" ]; do
    case "$1" in
      -a)
        shift
        [ "${1:-}" ] && attrs="${attrs:-} -a $1" || {
          echo "Please, specify the a value!"
          exit 1
        }
      ;;
      -t|--tag)
        shift
        [ "${1:-}" ] && tag=$1 || {
          echo "Please, specify the tag!"
          exit 1
        }
        git stash &> /dev/null
        git tag -l | grep -q "^$tag$" || {
          echo "Git tag is invalid!"
          git stash pop &> /dev/null
          exit 1
        }
        git checkout $tag &> /dev/null
        BUILD_DIR=$BUILD_DIR/$tag
      ;;
      -p) production=true;;
    esac
    shift || break
  done
  [ -f "$ADOC" ] || {
    >&2 echo "File \"$ADOC\" not found!"
    exit 1
  }
  echo -n "Building $ADOC "
  $production && echo "for production ..." || echo "for development ..."
  if ! $production && ! [ "${attrs:-}" ]; then attrs="-a env-localhost"; fi
  docker-asciidoctor asciidoctor -D "$BUILD_DIR" ${attrs:-} "$ADOC" -o index.html
  ! $GENERATE_PDF || docker-asciidoctor asciidoctor-pdf -D "$BUILD_DIR" ${attrs:-} "$ADOC" -o "`basename "$BASE_DIR"`.pdf"
  ! [ -d outputs ] || rsync -a outputs "$BUILD_DIR"/
  if [ "${tag:-}" ]; then
    git checkout master &> /dev/null
    git stash pop &> /dev/null || :
  fi
}

gh-pages() {
  [ -d $BUILD_DIR ] || { echo "\"$BUILD_DIR\" directory does not exists!"; return 1; }
  echo "Publish the contents in \"$BUILD_DIR\" to GitHub Pages ..."
  local msg="Published at `date`"
  cd "$BUILD_DIR"
  git init
  git add -A
  git commit -m "$msg"
  git push --force $REMOTE_REPO master:gh-pages
}

serve() {
  local serve_bin
  serve_bin=$(which serve 2> /dev/null) || {
    echo "The utility \"serve\" was not found in PATH!"
    return 1
  }
  $serve_bin -l $SERVE_PORT "$BUILD_DIR"
}

usage() {
  echo "Usage: $0 <[html] [-<t|-tag> <tag>]|gh-pages>"
  exit 0
}

if [ "${1:-}" ]; then
  [[ $1 =~ ^- ]] && { task=html; set -- html "$@"; } || task=$1
else
  task=html

fi
shift || :
type $task &> /dev/null || usage
$task ${@:-}

# vim: et ts=2 sw=2
